


CREATE TABLE ca_boundaries_bgc_tbl(FID INTEGER, CAUTH25CD VARCHAR, CAUTH25NM VARCHAR, BNG_E INTEGER, BNG_N INTEGER, LONG DOUBLE, LAT DOUBLE, Shape__Area DOUBLE, Shape__Length DOUBLE, GlobalID VARCHAR, geom GEOMETRY);
CREATE TABLE ca_emissions_evidence_long_tbl(region_country VARCHAR, local_authority VARCHAR, local_authority_code VARCHAR, calendar_year BIGINT, population_000s_mid_year_estimate DOUBLE, per_capita_emissions_t_co2e DOUBLE, area_km2 DOUBLE, emissions_per_km2_kt_co2e DOUBLE, sector VARCHAR, total_bool BOOLEAN, grand_total DOUBLE, emissions_kt_co2e DOUBLE, cauthcd VARCHAR, cauthnm VARCHAR);
CREATE TABLE ca_la_dft_lookup_tbl(dft_la_id BIGINT, ladcd VARCHAR, "year" BIGINT);
CREATE TABLE ca_la_tbl(ladcd VARCHAR, ladnm VARCHAR, cauthcd VARCHAR, cauthnm VARCHAR);
CREATE TABLE emissions_tbl(region_country VARCHAR, second_tier_authority VARCHAR, local_authority VARCHAR, local_authority_code VARCHAR, calendar_year BIGINT, industry_electricity DOUBLE, industry_gas DOUBLE, large_industrial_installations DOUBLE, industry_other DOUBLE, industry_total DOUBLE, commercial_electricity DOUBLE, commercial_gas DOUBLE, commercial_other DOUBLE, commercial_total DOUBLE, public_sector_electricity DOUBLE, public_sector_gas DOUBLE, public_sector_other DOUBLE, public_sector_total DOUBLE, domestic_electricity DOUBLE, domestic_gas DOUBLE, domestic_other DOUBLE, domestic_total DOUBLE, road_transport_a_roads DOUBLE, road_transport_motorways DOUBLE, road_transport_minor_roads DOUBLE, diesel_railways DOUBLE, transport_other DOUBLE, transport_total DOUBLE, net_emissions_forestry DOUBLE, net_emissions_cropland_mineral_soils_change DOUBLE, net_emissions_grassland_mineral_soils_change DOUBLE, net_emissions_settlements DOUBLE, net_emissions_peatland DOUBLE, net_emissions_bioenergy_crops DOUBLE, net_emissions_other_lulucf DOUBLE, lulucf_net_emissions DOUBLE, agriculture_electricity DOUBLE, agriculture_gas DOUBLE, agriculture_other DOUBLE, agriculture_livestock DOUBLE, agriculture_soils DOUBLE, agriculture_total DOUBLE, landfill DOUBLE, waste_other DOUBLE, waste_total DOUBLE, grand_total DOUBLE, population_000s_mid_year_estimate DOUBLE, per_capita_emissions_t_co2e DOUBLE, area_km2 DOUBLE, emissions_per_km2_kt_co2e DOUBLE);
CREATE TABLE epc_domestic_tbl(LMK_KEY VARCHAR, ADDRESS1 VARCHAR, ADDRESS2 VARCHAR, ADDRESS3 VARCHAR, POSTCODE VARCHAR, BUILDING_REFERENCE_NUMBER VARCHAR, CURRENT_ENERGY_RATING VARCHAR, POTENTIAL_ENERGY_RATING VARCHAR, CURRENT_ENERGY_EFFICIENCY INTEGER, POTENTIAL_ENERGY_EFFICIENCY INTEGER, PROPERTY_TYPE VARCHAR, BUILT_FORM VARCHAR, INSPECTION_DATE DATE, LOCAL_AUTHORITY VARCHAR, CONSTITUENCY VARCHAR, COUNTY VARCHAR, LODGEMENT_DATE DATE, TRANSACTION_TYPE VARCHAR, ENVIRONMENT_IMPACT_CURRENT INTEGER, ENVIRONMENT_IMPACT_POTENTIAL INTEGER, ENERGY_CONSUMPTION_CURRENT DOUBLE, ENERGY_CONSUMPTION_POTENTIAL DOUBLE, CO2_EMISSIONS_CURRENT DECIMAL(10,2), CO2_EMISS_CURR_PER_FLOOR_AREA DECIMAL(10,2), CO2_EMISSIONS_POTENTIAL DECIMAL(10,2), LIGHTING_COST_CURRENT DOUBLE, LIGHTING_COST_POTENTIAL DOUBLE, HEATING_COST_CURRENT DOUBLE, HEATING_COST_POTENTIAL DOUBLE, HOT_WATER_COST_CURRENT DOUBLE, HOT_WATER_COST_POTENTIAL DOUBLE, TOTAL_FLOOR_AREA DECIMAL(10,2), ENERGY_TARIFF VARCHAR, MAINS_GAS_FLAG VARCHAR, FLOOR_LEVEL VARCHAR, FLAT_TOP_STOREY VARCHAR, FLAT_STOREY_COUNT DECIMAL(10,2), MAIN_HEATING_CONTROLS VARCHAR, MULTI_GLAZE_PROPORTION DOUBLE, GLAZED_TYPE VARCHAR, GLAZED_AREA VARCHAR, EXTENSION_COUNT INTEGER, NUMBER_HABITABLE_ROOMS DOUBLE, NUMBER_HEATED_ROOMS DOUBLE, LOW_ENERGY_LIGHTING INTEGER, NUMBER_OPEN_FIREPLACES INTEGER, HOTWATER_DESCRIPTION VARCHAR, HOT_WATER_ENERGY_EFF VARCHAR, HOT_WATER_ENV_EFF VARCHAR, FLOOR_DESCRIPTION VARCHAR, FLOOR_ENERGY_EFF VARCHAR, FLOOR_ENV_EFF VARCHAR, WINDOWS_DESCRIPTION VARCHAR, WINDOWS_ENERGY_EFF VARCHAR, WINDOWS_ENV_EFF VARCHAR, WALLS_DESCRIPTION VARCHAR, WALLS_ENERGY_EFF VARCHAR, WALLS_ENV_EFF VARCHAR, SECONDHEAT_DESCRIPTION VARCHAR, SHEATING_ENERGY_EFF VARCHAR, SHEATING_ENV_EFF VARCHAR, ROOF_DESCRIPTION VARCHAR, ROOF_ENERGY_EFF VARCHAR, ROOF_ENV_EFF VARCHAR, MAINHEAT_DESCRIPTION VARCHAR, MAINHEAT_ENERGY_EFF VARCHAR, MAINHEAT_ENV_EFF VARCHAR, MAINHEATCONT_DESCRIPTION VARCHAR, MAINHEATC_ENERGY_EFF VARCHAR, MAINHEATC_ENV_EFF VARCHAR, LIGHTING_DESCRIPTION VARCHAR, LIGHTING_ENERGY_EFF VARCHAR, LIGHTING_ENV_EFF VARCHAR, MAIN_FUEL VARCHAR, WIND_TURBINE_COUNT DOUBLE, HEAT_LOSS_CORRIDOR VARCHAR, UNHEATED_CORRIDOR_LENGTH DECIMAL(10,2), FLOOR_HEIGHT DECIMAL(10,2), PHOTO_SUPPLY DOUBLE, SOLAR_WATER_HEATING_FLAG VARCHAR, MECHANICAL_VENTILATION VARCHAR, PROPERTY_ADDRESS VARCHAR, LOCAL_AUTHORITY_LABEL VARCHAR, CONSTITUENCY_LABEL VARCHAR, POSTTOWN VARCHAR, CONSTRUCTION_AGE_BAND VARCHAR, LODGEMENT_DATETIME TIMESTAMP, TENURE VARCHAR, FIXED_LIGHTING_OUTLETS_COUNT DOUBLE, LOW_ENERGY_FIXED_LIGHT_COUNT DOUBLE, UPRN VARCHAR, UPRN_SOURCE VARCHAR, REPORT_TYPE INTEGER);
CREATE TABLE epc_nondom_tbl(LMK_KEY VARCHAR, ADDRESS1 VARCHAR, ADDRESS2 VARCHAR, ADDRESS3 VARCHAR, POSTCODE VARCHAR, BUILDING_REFERENCE_NUMBER VARCHAR, ASSET_RATING INTEGER, ASSET_RATING_BAND VARCHAR, PROPERTY_TYPE VARCHAR, INSPECTION_DATE DATE, LOCAL_AUTHORITY VARCHAR, CONSTITUENCY VARCHAR, COUNTY VARCHAR, LODGEMENT_DATE DATE, TRANSACTION_TYPE VARCHAR, NEW_BUILD_BENCHMARK VARCHAR, EXISTING_STOCK_BENCHMARK VARCHAR, BUILDING_LEVEL VARCHAR, MAIN_HEATING_FUEL VARCHAR, OTHER_FUEL_DESC VARCHAR, SPECIAL_ENERGY_USES VARCHAR, RENEWABLE_SOURCES VARCHAR, FLOOR_AREA INTEGER, STANDARD_EMISSIONS DECIMAL(10,2), TARGET_EMISSIONS DECIMAL(10,2), TYPICAL_EMISSIONS DECIMAL(10,2), BUILDING_EMISSIONS DECIMAL(10,2), AIRCON_PRESENT VARCHAR, AIRCON_KW_RATING DECIMAL(10,2), ESTIMATED_AIRCON_KW_RATING DECIMAL(10,2), AC_INSPECTION_COMMISSIONED INTEGER, BUILDING_ENVIRONMENT VARCHAR, ADDRESS VARCHAR, LOCAL_AUTHORITY_LABEL VARCHAR, CONSTITUENCY_LABEL VARCHAR, POSTTOWN VARCHAR, LODGEMENT_DATETIME TIMESTAMP, PRIMARY_ENERGY_VALUE INTEGER, UPRN BIGINT, UPRN_SOURCE VARCHAR, REPORT_TYPE INTEGER);
CREATE TABLE ghg_emissions_tbl(country VARCHAR, country_code VARCHAR, region VARCHAR, region_code VARCHAR, second_tier_authority VARCHAR, local_authority VARCHAR, local_authority_code VARCHAR, calendar_year BIGINT, la_ghg_sector VARCHAR, la_ghg_sub_sector VARCHAR, greenhouse_gas VARCHAR, territorial_emissions_kt_co2e DOUBLE, emissions_within_the_scope_of_influence_of_las_kt_co2 DOUBLE, mid_year_population_thousands DOUBLE, area_km2 DOUBLE);
CREATE TABLE imd_lsoa_tbl(lsoa11cd VARCHAR, income_deprivation_domain_rank BIGINT, index_of_multiple_deprivation_imd_decile BIGINT, employment_deprivation_domain_rank BIGINT, education_skills_and_training_domain_rank BIGINT, income_deprivation_affecting_older_people_index_idaopi_decile BIGINT, income_deprivation_affecting_children_index_idaci_decile BIGINT, crime_domain_rank BIGINT, education_skills_and_training_domain_decile BIGINT, employment_deprivation_domain_decile BIGINT, health_deprivation_and_disability_domain_rank BIGINT, income_deprivation_affecting_children_index_idaci_rank BIGINT, health_deprivation_and_disability_domain_decile BIGINT, living_environment_deprivation_domain_decile BIGINT, income_deprivation_domain_decile BIGINT, crime_domain_decile BIGINT, barriers_to_housing_and_services_domain_decile BIGINT, income_deprivation_affecting_older_people_index_idaopi_score BIGINT, income_deprivation_affecting_children_index_idaci_score BIGINT, education_skills_and_training_domain_score BIGINT, barriers_to_housing_and_services_domain_score BIGINT, living_environment_deprivation_domain_score BIGINT, crime_domain_score BIGINT, health_deprivation_and_disability_domain_score BIGINT, employment_deprivation_domain_score BIGINT, index_of_multiple_deprivation_imd_rank BIGINT, income_deprivation_affecting_older_people_index_idaopi_rank BIGINT, barriers_to_housing_and_services_domain_rank BIGINT, living_environment_deprivation_domain_rank BIGINT, income_deprivation_domain_score BIGINT, index_of_multiple_deprivation_imd_score BIGINT);
CREATE TABLE la_all_mysoc_tbl("local-authority-code" VARCHAR, "official-name" VARCHAR, "nice-name" VARCHAR, "gss-code" VARCHAR, "start-date" DATE, "end-date" DATE, "replaced-by" VARCHAR, nation VARCHAR, region VARCHAR, "local-authority-type" VARCHAR, "local-authority-type-name" VARCHAR, "county-la" VARCHAR, "combined-authority" VARCHAR, "alt-names" VARCHAR, "former-gss-codes" VARCHAR, notes VARCHAR, "current-authority" BOOLEAN, "BS-6879" VARCHAR, ecode VARCHAR, "even-older-register-and-code" VARCHAR, "gov-uk-slug" VARCHAR, area DOUBLE, "pop-2020" DOUBLE, x DOUBLE, y DOUBLE, lat DOUBLE, long DOUBLE, powers VARCHAR, "lower-or-unitary" BOOLEAN, "mapit-area-code" VARCHAR, ofcom VARCHAR, "old-ons-la-code" VARCHAR, "old-register-and-code" VARCHAR, "open-council-data-id" DOUBLE, "os-file" VARCHAR, os DOUBLE, snac VARCHAR, "wdtk-id" DOUBLE);
CREATE TABLE lsoa_2011_lookup_tbl(lsoa01cd VARCHAR, lsoa01nm VARCHAR, lsoa11cd VARCHAR, lsoa11nm VARCHAR, chgind VARCHAR, lad11cd VARCHAR, lad11nm VARCHAR, lad11nmw VARCHAR, fid BIGINT);
CREATE TABLE lsoa_2021_lookup_tbl(lsoa21cd VARCHAR, lsoa21nm VARCHAR, lsoa21nmw VARCHAR, wd24cd VARCHAR, wd24nm VARCHAR, wd24nmw VARCHAR, lad24cd VARCHAR, lad24nm VARCHAR, lad24nmw VARCHAR, objectid BIGINT);
CREATE TABLE lsoa_2021_pwc_tbl(fid BIGINT, lsoa21cd VARCHAR, x DOUBLE, y DOUBLE, geom GEOMETRY);
CREATE TABLE lsoa_poly_2011_tbl(FID INTEGER, LSOA11CD VARCHAR, LSOA11NM VARCHAR, LSOA11NMW VARCHAR, BNG_E INTEGER, BNG_N INTEGER, LONG FLOAT, LAT FLOAT, Shape__Area DOUBLE, Shape__Length DOUBLE, GlobalID VARCHAR, geometry GEOMETRY, geom GEOMETRY);
CREATE TABLE lsoa_poly_2021_tbl(FID INTEGER, LSOA21CD VARCHAR, LSOA21NM VARCHAR, LSOA21NMW VARCHAR, BNG_E INTEGER, BNG_N INTEGER, LAT FLOAT, LONG FLOAT, Shape__Area DOUBLE, Shape__Length DOUBLE, GlobalID VARCHAR, geometry GEOMETRY, geom GEOMETRY);
CREATE TABLE postcodes_tbl(pcd7 VARCHAR, pcd8 VARCHAR, pcds VARCHAR, dointr BIGINT, doterm BIGINT, cty25cd VARCHAR, ced25cd VARCHAR, lad25cd VARCHAR, wd25cd VARCHAR, parncp25cd VARCHAR, usrtypind BIGINT, east1m BIGINT, north1m BIGINT, gridind BIGINT, hlth19cd VARCHAR, nhser24cd VARCHAR, ctry25cd VARCHAR, rgn25cd VARCHAR, ssr95cd VARCHAR, pcon24cd VARCHAR, eer20cd VARCHAR, educ23cd VARCHAR, ttwa15cd VARCHAR, pco19cd VARCHAR, itl25cd VARCHAR, wdstl05cd VARCHAR, oa01cd VARCHAR, wdcas03cd VARCHAR, npark16cd VARCHAR, lsoa01cd VARCHAR, msoa01cd VARCHAR, ruc01ind VARCHAR, oac01ind VARCHAR, oa11cd VARCHAR, lsoa11cd VARCHAR, msoa11cd VARCHAR, wz11cd VARCHAR, sicbl24cd VARCHAR, bua24cd VARCHAR, ruc11ind VARCHAR, oac11ind VARCHAR, lat DOUBLE, long DOUBLE, lep21cd1 VARCHAR, lep21cd2 VARCHAR, pfa23cd VARCHAR, imd20ind BIGINT, cal24cd VARCHAR, icb23cd VARCHAR, oa21cd VARCHAR, lsoa21cd VARCHAR, msoa21cd VARCHAR, ruc21ind VARCHAR, geom GEOMETRY);
CREATE TABLE postcode_lookup_tbl(pcd7 VARCHAR, pcd8 VARCHAR, pcds VARCHAR, dointr BIGINT, doterm BIGINT, usrtypind BIGINT, east1m BIGINT, north1m BIGINT, gridind BIGINT, oa21cd VARCHAR, cty25cd VARCHAR, ced25cd VARCHAR, lad25cd VARCHAR, wd25cd VARCHAR, nhser24cd VARCHAR, ctry25cd VARCHAR, rgn25cd VARCHAR, pcon24cd VARCHAR, ttwa15cd VARCHAR, itl25cd VARCHAR, npark16cd VARCHAR, lsoa21cd VARCHAR, msoa21cd VARCHAR, wz11cd VARCHAR, sicbl24cd VARCHAR, bua24cd VARCHAR, ruc21ind VARCHAR, oac11ind VARCHAR, lat DOUBLE, long DOUBLE, lep21cd1 VARCHAR, lep21cd2 VARCHAR, pfa23cd VARCHAR, imd20ind BIGINT, icb23cd VARCHAR);
CREATE TABLE tenure_tbl(lsoa_name VARCHAR, lsoa21cd VARCHAR, total_all_households BIGINT, "owned" BIGINT, shared_ownership BIGINT, social_rented BIGINT, private_rented BIGINT, lives_rent_free BIGINT, owns_with_a_mortgage_or_loan_or_shared_ownership BIGINT, private_rented_or_lives_rent_free BIGINT);

CREATE VIEW ca_la_ghg_emissions_sub_sector_ods_vw AS WITH joined_data AS (SELECT * FROM ghg_emissions_tbl AS ghg INNER JOIN ca_la_tbl AS ca ON ((ghg.local_authority_code = ca.ladcd)))SELECT * EXCLUDE (country, ladnm, ladcd, country_code, region, second_tier_authority) FROM joined_data;
CREATE VIEW epc_domestic_lep_vw AS SELECT * FROM epc_domestic_vw WHERE ((local_authority = ANY(SELECT ladcd FROM ca_la_tbl WHERE (cauthnm = 'West of England'))) AND (long BETWEEN -3.1178 AND -2.25211) AND (lat BETWEEN 51.273 AND 51.68239));
CREATE VIEW epc_domestic_ods_vw AS SELECT LMK_KEY AS lmk_key, UPRN AS uprn, LOCAL_AUTHORITY AS local_authority, PROPERTY_TYPE AS property_type, TRANSACTION_TYPE AS transaction_type, TENURE_CLEAN AS tenure, WALLS_DESCRIPTION AS walls_description, ROOF_DESCRIPTION AS roof_description, WALLS_ENERGY_EFF AS walls_energy_eff, ROOF_ENERGY_EFF AS roof_energy_eff, MAINHEAT_DESCRIPTION AS mainheat_description, MAINHEAT_ENERGY_EFF AS mainheat_energy_eff, MAIN_FUEL AS main_fuel, SOLAR_WATER_HEATING_FLAG AS solar_water_heating_flag, CONSTRUCTION_AGE_BAND AS construction_age_band, CURRENT_ENERGY_RATING AS current_energy_rating, POTENTIAL_ENERGY_RATING AS potential_energy_rating, CO2_EMISSIONS_CURRENT AS co2_emissions_current, CO2_EMISSIONS_POTENTIAL AS co2_emissions_potential, CO2_EMISS_CURR_PER_FLOOR_AREA AS co2_emiss_curr_per_floor_area, NUMBER_HABITABLE_ROOMS AS number_habitable_rooms, NUMBER_HEATED_ROOMS AS number_heated_rooms, PHOTO_SUPPLY AS photo_supply, TOTAL_FLOOR_AREA AS total_floor_area, BUILDING_REFERENCE_NUMBER AS building_reference_number, BUILT_FORM AS built_form, lsoa21cd, msoa21cd, lat, long, index_of_multiple_deprivation_imd_rank AS imd20ind, total_all_households AS total, "owned", social_rented, private_rented, LODGEMENT_DATE AS date, LODGEMENT_YEAR AS "year", LODGEMENT_MONTH AS "month", index_of_multiple_deprivation_imd_decile AS n_imd_decile, NOMINAL_CONSTRUCTION_YEAR AS n_nominal_construction_date, CONSTRUCTION_EPOCH AS construction_epoch, LOCAL_AUTHORITY_LABEL AS ladnm, concat('{', lat, ', ', long, '}') AS geo_point_2d FROM epc_domestic_lep_vw;
CREATE VIEW epc_domestic_vw AS SELECT c.*, CASE  WHEN (regexp_matches(CONSTRUCTION_AGE_BAND, '(\d{4})-(\d{4})')) THEN (CAST(round(((CAST(regexp_extract(CONSTRUCTION_AGE_BAND, '(\d{4})-(\d{4})', 1) AS INTEGER) + CAST(regexp_extract(CONSTRUCTION_AGE_BAND, '(\d{4})-(\d{4})', 2) AS INTEGER)) / 2.0)) AS INTEGER)) WHEN (regexp_matches(CONSTRUCTION_AGE_BAND, 'before (\d{4})')) THEN (CAST(regexp_extract(CONSTRUCTION_AGE_BAND, 'before (\d{4})', 1) AS INTEGER)) WHEN (regexp_matches(CONSTRUCTION_AGE_BAND, '(\d{4}) onwards')) THEN (CAST(regexp_extract(CONSTRUCTION_AGE_BAND, '(\d{4}) onwards', 1) AS INTEGER)) WHEN (regexp_matches(CONSTRUCTION_AGE_BAND, '(\d{4})')) THEN (CAST(regexp_extract(CONSTRUCTION_AGE_BAND, '(\d{4})', 1) AS INTEGER)) ELSE NULL END AS NOMINAL_CONSTRUCTION_YEAR, CASE  WHEN ((NOMINAL_CONSTRUCTION_YEAR < 1900)) THEN ('Before 1900') WHEN (((NOMINAL_CONSTRUCTION_YEAR >= 1900) AND (NOMINAL_CONSTRUCTION_YEAR <= 1930))) THEN ('1900 - 1930') WHEN ((NOMINAL_CONSTRUCTION_YEAR > 1930)) THEN ('1930 to present') ELSE 'Unknown' END AS CONSTRUCTION_EPOCH, CASE  WHEN (((TENURE = 'owner-occupied') OR (TENURE = 'Owner-occupied'))) THEN ('Owner occupied') WHEN (((TENURE = 'Rented (social)') OR (TENURE = 'rental (social)'))) THEN ('Social rented') WHEN (((TENURE = 'rental (private)') OR (TENURE = 'Rented (private)'))) THEN ('Private rented') ELSE NULL END AS TENURE_CLEAN, date_part('day', c.LODGEMENT_DATETIME) AS LODGEMENT_DAY, date_part('month', c.LODGEMENT_DATETIME) AS LODGEMENT_MONTH, date_part('year', c.LODGEMENT_DATETIME) AS LODGEMENT_YEAR, postcodes_tbl.lsoa21cd, postcodes_tbl.msoa21cd, postcodes_tbl.lsoa11cd, postcodes_tbl.msoa11cd, postcodes_tbl.lat, postcodes_tbl.long, postcodes_tbl.north1m, postcodes_tbl.east1m, st_astext(postcodes_tbl.geom) AS geom_text, postcodes_tbl.imd20ind, postcodes_tbl.pcds, tenure_tbl.*, imd_lsoa_tbl.* FROM epc_domestic_tbl AS c INNER JOIN (SELECT UPRN, max(LODGEMENT_DATETIME) AS max_date FROM epc_domestic_tbl GROUP BY UPRN) AS latest ON (((c.UPRN = latest.UPRN) AND (c.LODGEMENT_DATETIME = latest.max_date))) LEFT JOIN postcodes_tbl ON ((c.POSTCODE = postcodes_tbl.pcds)) LEFT JOIN tenure_tbl ON ((postcodes_tbl.lsoa21cd = tenure_tbl.lsoa21cd)) LEFT JOIN imd_lsoa_tbl ON ((postcodes_tbl.lsoa11cd = imd_lsoa_tbl.lsoa11cd));
CREATE VIEW epc_non_domestic_ods_vw AS SELECT UPRN AS uprn, LMK_KEY AS lmk_key, BUILDING_REFERENCE_NUMBER AS building_reference_number, ASSET_RATING AS asset_rating, ASSET_RATING_BAND AS asset_rating_band, PROPERTY_TYPE AS property_type, LOCAL_AUTHORITY AS local_authority, CONSTITUENCY AS constituency, TRANSACTION_TYPE AS transaction_type, STANDARD_EMISSIONS AS standard_emissions, TYPICAL_EMISSIONS AS typical_emissions, TARGET_EMISSIONS AS target_emissions, BUILDING_EMISSIONS AS building_emissions, BUILDING_LEVEL AS building_level, RENEWABLE_SOURCES AS renewable_sources, LODGEMENT_DATE AS date, LODGEMENT_YEAR AS "year", LODGEMENT_MONTH AS "month", ladcd, ladnm, cauthcd, cauthnm, lsoa21cd, lat, long, concat('{', lat, ', ', long, '}') AS geo_point_2d FROM epc_non_domestic_vw WHERE ((long BETWEEN -3.1178 AND -2.25211) AND (lat BETWEEN 51.273 AND 51.68239));
CREATE VIEW epc_non_domestic_vw AS SELECT c.*, ca_la_tbl.*, p.lsoa21cd, p.lat, p.long, date_part('day', c.LODGEMENT_DATETIME) AS LODGEMENT_DAY, date_part('month', c.LODGEMENT_DATETIME) AS LODGEMENT_MONTH, date_part('year', c.LODGEMENT_DATETIME) AS LODGEMENT_YEAR FROM epc_nondom_tbl AS c INNER JOIN (SELECT UPRN, max(LODGEMENT_DATETIME) AS max_date FROM epc_nondom_tbl GROUP BY UPRN) AS latest ON (((c.UPRN = latest.UPRN) AND (c.LODGEMENT_DATETIME = latest.max_date))) INNER JOIN ca_la_tbl ON ((c.LOCAL_AUTHORITY = ca_la_tbl.ladcd)) INNER JOIN (SELECT pcds, lsoa21cd, lat, long FROM postcodes_tbl) AS p ON ((c.POSTCODE = p.pcds)) WHERE (c.LOCAL_AUTHORITY = ANY(SELECT ladcd FROM ca_la_tbl WHERE (ca_la_tbl.cauthnm = 'West of England')));
CREATE VIEW per_cap_emissions_ca_national_vw AS SELECT t6.calendar_year, t6.cauthnm AS area, (t6.gt_sum_ca / t6.pop_sum_ca) AS per_cap FROM (SELECT t5.cauthnm, t5.calendar_year, sum(t5.grand_total) AS gt_sum_ca, sum(t5.population_000s_mid_year_estimate) AS pop_sum_ca FROM (SELECT t2.region_country, t2.second_tier_authority, t2.local_authority, t2.local_authority_code, t2.calendar_year, t2.industry_electricity, t2.industry_gas, t2.large_industrial_installations, t2.industry_other, t2.industry_total, t2.commercial_electricity, t2.commercial_gas, t2.commercial_other, t2.commercial_total, t2.public_sector_electricity, t2.public_sector_gas, t2.public_sector_other, t2.public_sector_total, t2.domestic_electricity, t2.domestic_gas, t2.domestic_other, t2.domestic_total, t2.road_transport_a_roads, t2.road_transport_motorways, t2.road_transport_minor_roads, t2.diesel_railways, t2.transport_other, t2.transport_total, t2.net_emissions_forestry, t2.net_emissions_cropland_mineral_soils_change, t2.net_emissions_grassland_mineral_soils_change, t2.net_emissions_settlements, t2.net_emissions_peatland, t2.net_emissions_bioenergy_crops, t2.net_emissions_other_lulucf, t2.lulucf_net_emissions, t2.agriculture_electricity, t2.agriculture_gas, t2.agriculture_other, t2.agriculture_livestock, t2.agriculture_soils, t2.agriculture_total, t2.landfill, t2.waste_other, t2.waste_total, t2.grand_total, t2.population_000s_mid_year_estimate, t2.per_capita_emissions_t_co2e, t2.area_km2, t2.emissions_per_km2_kt_co2e, t4.ladcd, t4.ladnm, t4.cauthcd, t4.cauthnm FROM emissions_tbl AS t2 INNER JOIN (SELECT * FROM ca_la_tbl AS t1 WHERE (t1.ladnm != 'North Somerset')) AS t4 ON ((t2.local_authority_code = t4.ladcd))) AS t5 GROUP BY 1, 2) AS t6;
CREATE VIEW simple_geog_lookup_vw AS WITH woe_la_cte AS (SELECT ladcd, ladnm FROM ca_la_tbl WHERE (cauthnm = 'West of England'))SELECT COLUMNS('^ls|^ms|^lad|^pcd|^wd|^lad|^imd|lat|long') FROM postcodes_tbl AS pc INNER JOIN woe_la_cte ON ((pc.lad25cd = woe_la_cte.ladcd));

CREATE UNIQUE INDEX ca_la_dft_lookup_idx ON ca_la_dft_lookup_tbl(ladcd);
CREATE UNIQUE INDEX lmk_key_dom_idx ON epc_domestic_tbl(LMK_KEY);
CREATE UNIQUE INDEX lmk_key_nondom_idx ON epc_nondom_tbl(LMK_KEY);
CREATE UNIQUE INDEX lsoa11cd_imd_idx ON imd_lsoa_tbl(lsoa11cd);
CREATE UNIQUE INDEX lsoa11cd_poly_idx ON lsoa_poly_2011_tbl(lsoa11cd);
CREATE UNIQUE INDEX lsoa21cd_lookup_idx ON lsoa_2021_lookup_tbl(lsoa21cd);
CREATE UNIQUE INDEX lsoa21cd_poly_idx ON lsoa_poly_2021_tbl(lsoa21cd);
CREATE UNIQUE INDEX lsoacd_pwc_idx ON lsoa_2021_pwc_tbl(lsoa21cd);
CREATE UNIQUE INDEX lsoacd_tenure_idx ON tenure_tbl(lsoa21cd);
CREATE UNIQUE INDEX postcode_centroids_idx ON postcodes_tbl(pcds);


